@echo off
echo Starting Healthcare Application...
echo.
echo Stopping any existing process on port 3003...
for /f "tokens=5" %%a in ('netstat -aon ^| findstr :3003') do taskkill /F /PID %%a >nul 2>&1
echo.
echo Installing dependencies...
call npm install
echo.
echo Starting server on port 3003...
echo Opening browser...
echo.
set NODE_ENV=production
start http://localhost:3003
node server.js
pause